import { config } from "@/lib/config";
import { normalizedJobSchema, type NormalizedJob } from "@/lib/schemas";
import { fixedFetch } from "@/providers/core";
import { ProviderError, type JobProvider, type ProviderHealth, type ProviderSearchResult, type SearchRequest } from "@/providers/types";
type FtOffer = { id: string; intitule: string; description?: string; dateCreation?: string; lieuTravail?: { libelle?: string }; entreprise?: { nom?: string }; typeContratLibelle?: string; typeContrat?: string; origineOffre?: { urlOrigine?: string }; contact?: { urlPostulation?: string }; salaire?: { libelle?: string }; competences?: { libelle?: string }[] };
export class FranceTravailProvider implements JobProvider {
  id = "france_travail"; private token?: { value: string; expires: number };
  private async accessToken() { const env = config(); if (!env.FRANCE_TRAVAIL_CLIENT_ID || !env.FRANCE_TRAVAIL_CLIENT_SECRET) throw new ProviderError("AUTH", "France Travail OAuth credentials are not configured.", false); if (this.token && this.token.expires > Date.now() + 60_000) return this.token.value; const body = new URLSearchParams({ grant_type: "client_credentials", client_id: env.FRANCE_TRAVAIL_CLIENT_ID, client_secret: env.FRANCE_TRAVAIL_CLIENT_SECRET, scope: "api_offresdemploiv2 o2dsoffre" }); const response = await fixedFetch("https://entreprise.pole-emploi.fr/connexion/oauth2/access_token?realm=%2Fpartenaire", { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body }); const data = await response.json() as { access_token: string; expires_in?: number }; this.token = { value: data.access_token, expires: Date.now() + (data.expires_in ?? 1_200) * 1000 }; return data.access_token; }
  normalize(raw: unknown): NormalizedJob { const offer = raw as FtOffer; const original = offer.origineOffre?.urlOrigine || offer.contact?.urlPostulation; const sourceUrl = original || `https://candidat.francetravail.fr/offres/recherche/detail/${encodeURIComponent(offer.id)}`; return normalizedJobSchema.parse({ source: this.id, sourceJobId: offer.id, sourceUrl, applicationUrl: sourceUrl, companyName: offer.entreprise?.nom || "Employer not disclosed", title: offer.intitule, location: offer.lieuTravail?.libelle || "France", contractType: offer.typeContratLibelle || offer.typeContrat || "UNKNOWN", descriptionRaw: offer.description || "", descriptionClean: offer.description || "", skillsRequired: (offer.competences ?? []).map(item => item.libelle || "").filter(Boolean), publishedAt: offer.dateCreation ? new Date(offer.dateCreation).toISOString() : null, extractor: "france_travail_official_api", sourceMetadata: { salaryText: offer.salaire?.libelle } }); }
  async search(request: SearchRequest): Promise<ProviderSearchResult> { const token = await this.accessToken(); const jobs: NormalizedJob[] = []; let fetched = 0, invalid = 0; const warnings: string[] = []; const queries = request.queries.length ? request.queries : [""]; for (const query of queries.slice(0, 10)) { const params = new URLSearchParams({ motsCles: query, range: `0-${Math.min(149, request.maxJobs - 1)}`, sort: "1" }); try { const response = await fixedFetch(`https://api.francetravail.io/partenaire/offresdemploi/v2/offres/search?${params}`, { headers: { Authorization: `Bearer ${token}` } }); const data = await response.json() as { resultats?: FtOffer[] }; for (const raw of data.resultats ?? []) { fetched++; try { jobs.push(this.normalize(raw)); } catch { invalid++; } if (jobs.length >= request.maxJobs) break; } } catch (error) { warnings.push(`${query || "all jobs"}: ${(error as Error).message}`); } if (jobs.length >= request.maxJobs) break; } return { jobs, stats: { fetched, valid: jobs.length, invalid }, warnings }; }
  async fetchDetails(url: string) { const id = url.split("/").pop(); if (!id) throw new ProviderError("PARSER_CHANGED", "Missing offer ID.", false); const token = await this.accessToken(); const response = await fixedFetch(`https://api.francetravail.io/partenaire/offresdemploi/v2/offres/${encodeURIComponent(id)}`, { headers: { Authorization: `Bearer ${token}` } }); return this.normalize(await response.json()); }
  async healthCheck(): Promise<ProviderHealth> { try { await this.accessToken(); return { status: "HEALTHY", detail: "Official API credentials accepted." }; } catch (error) { return { status: "DEGRADED", detail: (error as Error).message }; } }
}
