import * as cheerio from "cheerio";
import robotsParser from "robots-parser";
import { normalizedJobSchema, type NormalizedJob } from "@/lib/schemas";
import { cleanText, safePublicFetch } from "@/providers/core";
import { ProviderError, type JobProvider, type ProviderConfig, type ProviderHealth, type ProviderSearchResult, type SearchRequest } from "@/providers/types";

type JsonLd = Record<string, unknown>;
function values(value: unknown): JsonLd[] { if (Array.isArray(value)) return value.flatMap(values); if (!value || typeof value !== "object") return []; const object = value as JsonLd; return [object, ...values(object["@graph"])]; }
function text(value: unknown) { return typeof value === "string" ? value : ""; }
function named(value: unknown) { return value && typeof value === "object" ? text((value as JsonLd).name) : text(value); }
function location(value: unknown) { const item = Array.isArray(value) ? value[0] : value; if (!item || typeof item !== "object") return "France"; const address = (item as JsonLd).address; if (!address || typeof address !== "object") return named(item) || "France"; const record = address as JsonLd; return [text(record.addressLocality), text(record.addressRegion), text(record.addressCountry)].filter(Boolean).join(", ") || "France"; }
function salary(value: unknown, which: "minValue" | "maxValue") { if (!value || typeof value !== "object") return null; const record = value as JsonLd; const inner = record.value && typeof record.value === "object" ? record.value as JsonLd : record; const number = Number(inner[which] ?? inner.value); return Number.isFinite(number) && number >= 0 ? Math.round(number) : null; }

export class GenericProvider implements JobProvider {
  id = "generic"; constructor(private config: ProviderConfig) {}
  normalize(raw: unknown): NormalizedJob { const { item, pageUrl } = raw as { item: JsonLd; pageUrl: string }; const organization = item.hiringOrganization; const company = organization && typeof organization === "object" ? named(organization) : named(organization); const identifier = item.identifier && typeof item.identifier === "object" ? text((item.identifier as JsonLd).value) : text(item.identifier); const description = text(item.description); const employment = Array.isArray(item.employmentType) ? item.employmentType.join(", ") : text(item.employmentType); const workplace = text(item.jobLocationType).toUpperCase(); return normalizedJobSchema.parse({ source: this.id, sourceJobId: identifier || `${pageUrl}#${text(item.title)}`, sourceUrl: text(item.url) || pageUrl, applicationUrl: text(item.url) || pageUrl, companyName: company || new URL(pageUrl).hostname, companyDomain: new URL(pageUrl).hostname, title: text(item.title), location: location(item.jobLocation), remoteType: workplace.includes("TELECOMMUTE") ? "REMOTE" : "UNKNOWN", contractType: employment || "UNKNOWN", salaryMin: salary(item.baseSalary, "minValue"), salaryMax: salary(item.baseSalary, "maxValue"), salaryCurrency: item.baseSalary && typeof item.baseSalary === "object" ? text((item.baseSalary as JsonLd).currency) || "EUR" : "EUR", descriptionRaw: description, descriptionClean: cleanText(description), publishedAt: text(item.datePosted) ? new Date(text(item.datePosted)).toISOString() : null, expiresAt: text(item.validThrough) ? new Date(text(item.validThrough)).toISOString() : null, extractor: "schema_org_jobposting", sourceMetadata: {} }); }
  private async extract(pageUrl: string) { const url = new URL(pageUrl); const allowed = this.config.allowedHosts ?? []; const robotsUrl = `${url.origin}/robots.txt`; const robotsResponse = await safePublicFetch(robotsUrl, allowed).catch(() => null); if (robotsResponse) { const robots = robotsParser(robotsUrl, robotsResponse.body); if (!robots.isAllowed(pageUrl, "ElanJobSearch")) throw new ProviderError("BLOCKED", "robots.txt disallows this URL.", false); } const response = await safePublicFetch(pageUrl, allowed); if (response.status === 401 || response.status === 403) throw new ProviderError("BLOCKED", `Public access rejected with HTTP ${response.status}.`, false); if (response.status < 200 || response.status >= 300) throw new ProviderError("NETWORK", `Career page returned HTTP ${response.status}.`, response.status >= 500); const $ = cheerio.load(response.body); const results: NormalizedJob[] = []; $("script[type='application/ld+json']").each((_index, element) => { try { const data: unknown = JSON.parse($(element).text()); for (const item of values(data)) if (item["@type"] === "JobPosting") results.push(this.normalize({ item, pageUrl: response.url })); } catch { /* malformed unrelated structured data is ignored */ } }); return results; }
  async search(request: SearchRequest): Promise<ProviderSearchResult> { const jobs: NormalizedJob[] = []; let invalid = 0, fetched = 0; const warnings: string[] = []; if (!(this.config.urls?.length) || !(this.config.allowedHosts?.length)) warnings.push("Add HTTPS career URLs and matching allowed hosts."); for (const url of this.config.urls ?? []) { try { const extracted = await this.extract(url); fetched += extracted.length; jobs.push(...extracted.slice(0, Math.max(0, request.maxJobs - jobs.length))); if (!extracted.length) invalid++; } catch (error) { warnings.push(`${new URL(url).hostname}: ${(error as Error).message}`); } if (jobs.length >= request.maxJobs) break; } return { jobs, stats: { fetched, valid: jobs.length, invalid }, warnings }; }
  async fetchDetails(url: string) { const jobs = await this.extract(url); if (!jobs[0]) throw new ProviderError("PARSER_CHANGED", "No schema.org JobPosting found.", false); return jobs[0]; }
  async healthCheck(): Promise<ProviderHealth> { return { status: this.config.urls?.length && this.config.allowedHosts?.length ? "HEALTHY" : "DEGRADED", detail: this.config.urls?.length ? "Allowlisted JSON-LD pages configured." : "No career pages configured." }; }
}
