import { normalizedJobSchema, type NormalizedJob } from "@/lib/schemas";
import { cleanText, fixedFetch, jobMatches, publishedRecently } from "@/providers/core";
import { ProviderError, type JobProvider, type ProviderConfig, type ProviderHealth, type ProviderSearchResult, type SearchRequest } from "@/providers/types";
type LeverJob = { id: string; text: string; hostedUrl: string; applyUrl: string; createdAt?: number; descriptionPlain?: string; description?: string; categories?: { location?: string; commitment?: string; team?: string }; workplaceType?: string };
export class LeverProvider implements JobProvider {
  id = "lever"; constructor(private config: ProviderConfig) {}
  normalize(raw: unknown): NormalizedJob { const { job, board } = raw as { job: LeverJob; board: string }; const remote = job.workplaceType?.toLowerCase(); return normalizedJobSchema.parse({ source: this.id, sourceJobId: job.id, sourceUrl: job.hostedUrl, applicationUrl: job.applyUrl || job.hostedUrl, companyName: board, title: job.text, location: job.categories?.location || "France", remoteType: remote === "remote" ? "REMOTE" : remote === "hybrid" ? "HYBRID" : remote === "onsite" ? "ONSITE" : "UNKNOWN", contractType: job.categories?.commitment || "UNKNOWN", descriptionRaw: job.descriptionPlain || job.description || "", descriptionClean: cleanText(job.descriptionPlain || job.description || ""), publishedAt: job.createdAt ? new Date(job.createdAt).toISOString() : null, extractor: "lever_public_postings_api", sourceMetadata: { board, team: job.categories?.team } }); }
  async search(request: SearchRequest): Promise<ProviderSearchResult> { const jobs: NormalizedJob[] = []; let fetched = 0, invalid = 0; const warnings: string[] = []; for (const board of this.config.boards ?? []) { try { const response = await fixedFetch(`https://api.lever.co/v0/postings/${encodeURIComponent(board)}?mode=json`); const data = await response.json() as LeverJob[]; for (const raw of data) { fetched++; try { const job = this.normalize({ job: raw, board }); if (jobMatches(`${job.title} ${job.location} ${job.descriptionClean}`, request.queries, request.locations) && publishedRecently(job.publishedAt, request.datePostedWindow)) jobs.push(job); } catch { invalid++; } if (jobs.length >= request.maxJobs) break; } } catch (error) { warnings.push(`${board}: ${(error as Error).message}`); } if (jobs.length >= request.maxJobs) break; } if (!this.config.boards?.length) warnings.push("Add Lever site slugs in provider settings."); return { jobs, stats: { fetched, valid: jobs.length, invalid }, warnings }; }
  async fetchDetails(url: string) { const job = (await this.search({ queries: [], locations: [], remotePreferences: [], datePostedWindow: 30, maxJobs: 500 })).jobs.find(item => item.sourceUrl === url); if (!job) throw new ProviderError("PARSER_CHANGED", "Job not found.", false); return job; }
  async healthCheck(): Promise<ProviderHealth> { return { status: this.config.boards?.length ? "HEALTHY" : "DEGRADED", detail: this.config.boards?.length ? "Public postings API configured." : "No site slugs configured." }; }
}
