import { NextRequest, NextResponse } from "next/server";
import type { Prisma } from "@prisma/client";
import { assertSameOrigin, parseBody, requireUser, routeError } from "@/lib/api";
import { hash } from "@/lib/deduplication";
import { db } from "@/lib/db";
import { manualJobSchema, normalizedJobSchema } from "@/lib/schemas";
import { ingestJob, jobInclude, serializeJob } from "@/lib/services/jobs";

export async function GET(request: NextRequest) { try { await requireUser(); const query = request.nextUrl.searchParams; const page = Math.max(1, Number(query.get("page")) || 1), pageSize = 25; const minimum = Number(query.get("score")); const salaryMin = Number(query.get("salaryMin")); const where: Prisma.JobWhereInput = { ...(query.get("q") ? { OR: [{ title: { contains: query.get("q")!, mode: "insensitive" } }, { companyName: { contains: query.get("q")!, mode: "insensitive" } }, { descriptionClean: { contains: query.get("q")!, mode: "insensitive" } }] } : {}), ...(Number.isFinite(minimum) && query.has("score") ? { matchScore: { gte: minimum } } : {}), ...(query.get("provider") ? { sources: { some: { provider: query.get("provider")! } } } : {}), ...(query.get("company") ? { companyName: { contains: query.get("company")!, mode: "insensitive" } } : {}), ...(query.get("location") ? { location: { contains: query.get("location")!, mode: "insensitive" } } : {}), ...(query.get("remoteType") ? { remoteType: query.get("remoteType")! } : {}), ...(Number.isFinite(salaryMin) && query.has("salaryMin") ? { salaryMax: { gte: salaryMin } } : {}), ...(query.get("contractType") ? { contractType: { contains: query.get("contractType")!, mode: "insensitive" } } : {}), ...(query.get("status") ? { application: { status: query.get("status") as never } } : {}), ...(query.get("publishedDays") ? { publishedAt: { gte: new Date(Date.now() - Number(query.get("publishedDays")) * 86_400_000) } } : {}), ...(query.get("discoveredDays") ? { discoveredAt: { gte: new Date(Date.now() - Number(query.get("discoveredDays")) * 86_400_000) } } : {}) }; const sort = query.get("sort") ?? "score"; const orderBy: Prisma.JobOrderByWithRelationInput = sort === "newest" ? { discoveredAt: "desc" } : sort === "salary" ? { salaryMax: { sort: "desc", nulls: "last" } } : sort === "company" ? { companyName: "asc" } : sort === "published" ? { publishedAt: { sort: "desc", nulls: "last" } } : { matchScore: { sort: "desc", nulls: "last" } }; const [jobs, total] = await Promise.all([db.job.findMany({ where, include: jobInclude, orderBy, skip: (page - 1) * pageSize, take: pageSize }), db.job.count({ where })]); return NextResponse.json({ jobs: jobs.map(serializeJob), total, page, pageSize }); } catch (error) { return routeError(error); } }
export async function POST(request: NextRequest) { try { assertSameOrigin(request); await requireUser(); const input = await parseBody(request, manualJobSchema); const sourceId = hash(input.sourceUrl); const normalized = normalizedJobSchema.parse({ source: "manual", sourceJobId: sourceId, sourceUrl: input.sourceUrl, applicationUrl: input.applicationUrl ?? input.sourceUrl, companyName: input.companyName, title: input.title, location: input.location, remoteType: input.remoteType, contractType: input.contractType, salaryMin: input.salaryMin ?? null, salaryMax: input.salaryMax ?? null, descriptionRaw: input.descriptionClean, descriptionClean: input.descriptionClean, extractor: "manual_import" }); const saved = await ingestJob(normalized); const job = await db.job.findUniqueOrThrow({ where: { id: saved.job.id }, include: jobInclude }); return NextResponse.json(serializeJob(job), { status: saved.duplicate ? 200 : 201 }); } catch (error) { return routeError(error); } }
